CREATE TABLE IF NOT EXISTS `rental_history` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `citizenid` VARCHAR(50) NOT NULL,
    `vehicle_model` VARCHAR(50) NOT NULL,
    `vehicle_label` VARCHAR(100) NOT NULL,
    `rental_price` INT NOT NULL DEFAULT 0,
    `payment_method` VARCHAR(20) NOT NULL DEFAULT 'bank',
    `start_date` DATETIME NOT NULL,
    `end_date` DATETIME NOT NULL,
    `location_index` INT NOT NULL DEFAULT 1,
    `status` ENUM('active', 'returned', 'expired') NOT NULL DEFAULT 'active',
    `returned_at` DATETIME DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `vehicle_plate` VARCHAR(8) DEFAULT NULL,
    `vehicle_spawned` TINYINT(1) DEFAULT 0,
    `vehicle_coords` TEXT DEFAULT NULL,
    `vehicle_heading` FLOAT DEFAULT 0,
    `vehicle_props` TEXT DEFAULT NULL,
    `late_fee_total` INT DEFAULT 0,
    `last_fee_time` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_citizenid` (`citizenid`),
    INDEX `idx_status` (`status`),
    INDEX `idx_spawned` (`vehicle_spawned`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
